version: '3.8'

services:
  app:
    env_file:
      - .env
    image: ${DOCKER_USERNAME}/${SPRING_IMAGE}  # TODO 배포 시 .env.local 추가
    build: ..
    restart: always
    platform: linux/amd64 # m1 환경에서만
    ports:
      - ${APP_LOCAL_PORT}:${APP_SERVER_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}