version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "${DB_LOCAL_PORT}:${DB_SERVER_PORT}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}