name: CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  secrets:
    environment: docker-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 환경 변수 파일 생성
        run: |
          touch .env
          echo "{{ secrets.ENV_VARS }}" >> .env

      - name: 빌드 권한 설정
        run: chmod +x gradlew

      - name: 빌드
        run: ./gradlew clean build -x test

      - name: 도커 이미지 생성 및 오리진에 푸시
        env:
          COMPOSE: "compose/docker-compose.yml"
          USER: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          APP: ${{ secrets.DOCKER_APP_NAME }}
        run: |
          docker login -u $USER -p $PASSWORD
          docker-compose -f $COMPOSE build
          docker push $USER/$APP

      - name: 배포
        uses: appleboy/ssh-action@master
        env:
          COMPOSE: "compose/docker-compose.yml"
          USER: ${{ secrets.DOCKER_USERNAME }}
          APP: ${{ secrets.DOCKER_APP_NAME }}
        with:
          host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }} # pem 키
          # 도커 작업
          script: |
            sudo docker-compose -f $COMPOSE down --rmi all
            sudo docker pull $USER/$APP:latest
            sudo docker-compose -f $COMPOSE up -d
